version: '3.8'
services:
  pgdb:
    image: "postgres:12"
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: "rust_test"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
      POSTGRES_ROOT_PASSWORD: "root"
    ports:
      - "5432:5432"
volumes:
  pg:
    name: postgresql
